spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

cors:
  allowed-origins:
    - https://app.hjeon.i234.me

app:
  cookie:
    secure: true

logging:
  level:
    root: WARN
    com.vanilla2hub: INFO
