spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001

logging:
  level:
    com.vanilla2hub: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
